Make the RegisterServiceWithConsul function configurable by options
scayle/common-go pull request #1
Opened 2020-10-27 19:03 UTC by aligator

2020-10-27 19:20 UTC, dominikbraun requested changes

2020-10-27 19:20 UTC, dominikbraun commented on consul.go
> +	port, err := strconv.Atoi(Port(cfg.defaultPort)[1:len(Port(cfg.defaultPort))])
Please explain this line in a brief comment, ideally with an example.

2020-10-27 19:20 UTC, dominikbraun commented on consul.go
> +func WithHTTPHealthCheck(defaultPort int) Option {
You may note in the GoDoc that this function starts a webserver for the sake of clarity.

2020-10-27 19:23 UTC, dominikbraun commented on consul.go
> +func WithHTTPHealthCheck(defaultPort int) Option {
Nevermind!

2020-10-27 19:27 UTC, aligator commented on consul.go
> +// From v1.0.0 on RegisterServiceWithConsul will not do this automatically anymore.
```suggestion
// From v1.0.0 on RegisterServiceWithConsul will not do this automatically anymore.
// To disable the health check completely (in < v1.0.0) just pass an empty registration modifier: WithRegistrationModifier(func(_){})
```

2020-10-27 19:31 UTC, aligator commented on consul.go
> +// Deprecated: To use a simple HTTP health service, use WithHTTPHealthCheck().
```suggestion
// Deprecation note: To use a simple HTTP health service, use WithHTTPHealthCheck().
```

2020-10-27 19:39 UTC, HilmerChristophAkaHuima requested changes
Some spelling errors and comments on the Port func

2020-10-27 19:39 UTC, HilmerChristophAkaHuima commented on consul.go
> +			log.Fatalf("wrong healt Port format %v", err)
```suggestion
			log.Fatalf("wrong health port format %v", err)
```

2020-10-27 19:39 UTC, HilmerChristophAkaHuima commented on consul.go
>  		log.Fatalf("wrong Port format %v", err)
Port => port

2020-10-27 19:39 UTC, HilmerChristophAkaHuima commented on consul.go
> +func Port(defaultPort int) string {
Maybe without ":"

2020-10-27 19:39 UTC, HilmerChristophAkaHuima commented on consul.go
> +func HealthPort(defaultPort int) string {
Maybe without ":"

2020-10-27 20:08 UTC, aligator commented on consul.go
> +	port, err := strconv.Atoi(Port(cfg.defaultPort)[1:len(Port(cfg.defaultPort))])
changed the Port function completely

2020-10-27 20:11 UTC, aligator commented on consul.go
> +func Port(defaultPort int) string {
replaced function completely

2020-10-27 20:12 UTC, aligator commented on consul.go
>  		log.Fatalf("wrong Port format %v", err)
this log doesn't exist anymore

2020-10-27 20:18 UTC, HilmerChristophAkaHuima approved these changes
All good :smile:

2020-10-27 20:19 UTC, dominikbraun submitted a review, later dismissed
LGTM

2020-10-27 21:46 UTC, dominikbraun submitted a review, later dismissed
LGTM

2020-10-27 22:15 UTC, HilmerChristophAkaHuima approved these changes
:metal:

2020-10-28 19:17 UTC, muhmuhhum reviewed
basst

2020-10-28 19:19 UTC, muhmuhhum approved these changes

2020-10-28 19:19 UTC, merged